# Generated by Django 5.2 on 2025-07-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='xp_to_next_level',
            field=models.IntegerField(default=10000),
        ),
    ]
