# Generated by Django 5.2 on 2025-07-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_xp_to_next_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='xp_to_next_level',
            field=models.IntegerField(default=100),
        ),
    ]
