# Generated by Django 5.2 on 2025-07-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_xp_to_next_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='goal',
            field=models.TextField(blank=True, help_text="User's main life goal"),
        ),
        migrations.AddField(
            model_name='profile',
            name='goal_progress',
            field=models.IntegerField(default=0, help_text='Goal progress percentage (0-100)'),
        ),
    ]
