# Generated by Django 5.2 on 2025-07-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_goal_profile_goal_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='due_date',
            field=models.DateField(blank=True, help_text='When this quest is due', null=True),
        ),
    ]
